In [204]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from yellowbrick.regressor import ResidualsPlot 
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
import numpy as np
import pandas as pd
from keras.layers import Dense, Dropout
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_transformer

In [205]:
base = pd.read_csv('credito.csv', sep=',')

In [206]:
base

IDCREDITO  Duracao  HistoricoCredito  Proposito  Valor  Investimentos  \
0            1        6                 0          1   1169              1   
1            2       48                 2          1   5951              2   
2            3       12                 1          2   2096              2   
3            4       42                 2          3   7882              2   
4            5       24                 3          4   4870              2   
..         ...      ...               ...        ...    ...            ...   
995        996       12                 2          3   1736              2   
996        997       30                 2          5   3857              2   
997        998       12                 2          1    804              2   
998        999       45                 2          1   1845              2   
999       1000       45                 1          5   4576              5   

     Emprego  TempoParcelamento  EstadoCivil  FiadorTerceiros  \
0        NaN                  4            4                3   
1        3.0                  2            1                3   
2        4.0                  2            4                3   
3        4.0                  2            4                4   
4        3.0                  3            4                3   
..       ...                ...          ...              ...   
995      4.0                  3            1                3   
996      3.0                  4            2                3   
997      2.0                  4            4                3   
998      3.0                  4            4                3   
999      5.0                  3            4                3   

     ResidenciaDesde  Idade  OutrosFinanciamentos  Habitacao  \
0                4.0     67                     3        1.0   
1                2.0     22                     3        1.0   
2                3.0     49                     3        1.0   
3                4.0     45                     3        2.0   
4                4.0     53                     3        2.0   
..               ...    ...                   ...        ...   
995              4.0     31                     3        1.0   
996              4.0     40                     3        1.0   
997              4.0     38                     3        1.0   
998              4.0     23                     3        2.0   
999              4.0     27                     3        1.0   

     EmprestimoExistente  Profissao  Dependentes  SocioEmpresa  Estrangeiro  \
0                      2          4            1             1            0   
1                      1          4            1             0            0   
2                      1          3            2             0            0   
3                      1          4            2             0            0   
4                      2          4            2             0            0   
..                   ...        ...          ...           ...          ...   
995                    1          3            1             0            0   
996                    1          1            1             1            0   
997                    1          4            1             0            0   
998                    1          4            1             1            0   
999                    1          4            1             0            0   

     Status  
0         1  
1         0  
2         1  
3         1  
4         0  
..      ...  
995       1  
996       1  
997       1  
998       0  
999       1  

[1000 rows x 20 columns]

In [207]:
base.shape


(1000, 20)

In [438]:
# after testing it was proven that if you remove column 11 , false true decreases by 11 %
x = base.iloc[:,[1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17]].values
x


array([[ 6.,  0.,  1., ...,  4.,  1.,  1.],
       [48.,  2.,  1., ...,  4.,  1.,  0.],
       [12.,  1.,  2., ...,  3.,  2.,  0.],
       ...,
       [12.,  2.,  1., ...,  4.,  1.,  0.],
       [45.,  2.,  1., ...,  4.,  1.,  1.],
       [45.,  1.,  5., ...,  4.,  1.,  0.]])

In [439]:
y = base.iloc[:, 19].values



In [440]:
y

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,

In [441]:
onehotencoder = make_column_transformer((OneHotEncoder(categories='auto', sparse=False), [1]), remainder="passthrough")
x = onehotencoder.fit_transform(x)
x = x[:,1:]

In [442]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=50)

In [443]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)




In [444]:
x_train = np.nan_to_num(x_train)
x_test = np.nan_to_num(x_test)


In [445]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rd = RandomForestClassifier(random_state=10,max_depth=18)
rd.fit(x_train, y_train)
previ = rd.predict(x_test)
acurr = accuracy_score(y_test , previ) * 100
acurr


72.66666666666667

In [446]:
y_pred = (previ>0.5)
y_pred

array([ True,  True, False, False,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [447]:
#The best result Prioritizinge the minimum of false true  
cm = confusion_matrix(y_test, previ)
cm

array([[ 27,  66],
       [ 16, 191]], dtype=int64)